-- LoaHub PostgreSQL schema for Supabase
-- 게시판, 게시글, 댓글 데이터를 위한 기본 스키마입니다.

CREATE TABLE IF NOT EXISTS boards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  board_type VARCHAR(20) NOT NULL,
  board_name VARCHAR(100) NOT NULL,
  class_code VARCHAR(50),
  class_name VARCHAR(100),
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_boards_type_order
  ON boards (board_type, sort_order);

CREATE TABLE IF NOT EXISTS board_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_type VARCHAR(20) NOT NULL,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_board_categories_type_code UNIQUE (board_type, code)
);

CREATE INDEX IF NOT EXISTS idx_board_categories_type_order
  ON board_categories (board_type, sort_order);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  category_code VARCHAR(50) NOT NULL,
  author VARCHAR(100) NOT NULL,
  view_count BIGINT NOT NULL DEFAULT 0,
  like_count BIGINT NOT NULL DEFAULT 0,
  comment_count BIGINT NOT NULL DEFAULT 0,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_posts_board FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT,
  CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_posts_board_status_created
  ON posts (board_id, status, pinned, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_posts_board_status_likes
  ON posts (board_id, status, like_count DESC);

CREATE INDEX IF NOT EXISTS idx_posts_board_status_views
  ON posts (board_id, status, view_count DESC);

CREATE INDEX IF NOT EXISTS idx_posts_board_status_comments
  ON posts (board_id, status, comment_count DESC);

CREATE INDEX IF NOT EXISTS idx_posts_category
  ON posts (category_code);

CREATE TABLE IF NOT EXISTS post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_post_likes_post_user UNIQUE (post_id, user_id),
  CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_post_likes_post_id
  ON post_likes (post_id);

CREATE INDEX IF NOT EXISTS idx_post_likes_user_id
  ON post_likes (user_id);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  author VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_post_status_created
  ON comments (post_id, status, created_at);

CREATE TABLE IF NOT EXISTS message_threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  last_message TEXT NOT NULL,
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sender_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  receiver_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_message_threads_sender FOREIGN KEY (sender_id) REFERENCES public.users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_message_threads_receiver FOREIGN KEY (receiver_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_message_threads_pair
  ON message_threads (sender_id, receiver_id);

CREATE INDEX IF NOT EXISTS idx_message_threads_last_message_at
  ON message_threads (last_message_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  read_yn BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_by_sender BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_by_receiver BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_messages_thread FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES public.users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id) REFERENCES public.users(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_thread_created
  ON messages (thread_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_messages_receiver_unread
  ON messages (receiver_id, read_yn, deleted_by_receiver);

INSERT INTO boards (id, slug, board_type, board_name, class_code, class_name, sort_order, status)
VALUES
  (1, 'free', 'FREE', '자유게시판', NULL, NULL, 1, 'ACTIVE'),
  (2, 'class/warlord', 'CLASS', '워로드 게시판', 'warlord', '워로드', 2, 'ACTIVE'),
  (3, 'class/paladin', 'CLASS', '팔라딘 게시판', 'paladin', '팔라딘', 3, 'ACTIVE'),
  (4, 'class/bard', 'CLASS', '바드 게시판', 'bard', '바드', 4, 'ACTIVE'),
  (5, 'class/sorceress', 'CLASS', '소서리스 게시판', 'sorceress', '소서리스', 5, 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO board_categories (id, board_type, code, name, sort_order, status)
VALUES
  (1, 'FREE', 'CHAT', '잡담', 1, 'ACTIVE'),
  (2, 'FREE', 'INFO', '정보', 2, 'ACTIVE'),
  (3, 'FREE', 'QUESTION', '질문', 3, 'ACTIVE'),
  (4, 'FREE', 'GUIDE', '공략', 4, 'ACTIVE'),
  (5, 'FREE', 'STREAM', '인방', 5, 'ACTIVE'),
  (6, 'FREE', 'FUN', '웃긴글', 6, 'ACTIVE'),
  (7, 'FREE', 'ETC', '기타', 7, 'ACTIVE'),
  (8, 'CLASS', 'CHAT', '잡담', 1, 'ACTIVE'),
  (9, 'CLASS', 'INFO', '정보', 2, 'ACTIVE'),
  (10, 'CLASS', 'QUESTION', '질문', 3, 'ACTIVE'),
  (11, 'CLASS', 'SETTING', '세팅', 4, 'ACTIVE'),
  (12, 'CLASS', 'DPS', '전분', 5, 'ACTIVE'),
  (13, 'CLASS', 'SKILL', '스킬트리', 6, 'ACTIVE'),
  (14, 'CLASS', 'ETC', '기타', 7, 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO posts (id, board_id, user_id, title, content, category_code, author, view_count, like_count, comment_count, pinned, status)
VALUES
  (1, 1, 1, '자유게시판 공지입니다', '이번 시즌 자유게시판 운영 안내와 기본 규칙을 정리한 공지입니다. 새 글 작성 전 꼭 확인해 주세요.', 'INFO', 'Guardian', 1250, 42, 8, TRUE, 'ACTIVE'),
  (2, 1, 1, '오늘의 레이드 파티 모집', '오늘 저녁 8시 기준으로 파티원 모집합니다. 탱커, 딜러, 서포터 모두 환영합니다.', 'CHAT', 'Guardian', 842, 16, 3, FALSE, 'ACTIVE'),
  (3, 1, 1, '초보자를 위한 공략 모음', '게임 시작 후 꼭 알아두면 좋은 공략과 팁을 한 번에 정리했습니다. 입문자 분들께 추천합니다.', 'GUIDE', 'Guardian', 5200, 33, 16, FALSE, 'ACTIVE'),
  (4, 2, 1, '워로드 세팅 가이드', '전투 특성과 각인, 장비 세팅 기준을 정리했습니다. 워로드 분들은 참고해 주세요.', 'SETTING', 'Guardian', 2940, 18, 4, TRUE, 'ACTIVE'),
  (5, 2, 1, '워로드 전분 비교 결과', '같은 조건으로 전분 테스트를 진행한 결과를 비교해 봤습니다. 참고용으로 봐 주세요.', 'DPS', 'Guardian', 1180, 21, 2, FALSE, 'ACTIVE'),
  (6, 3, 1, '팔라딘 질문 있습니다', '각인 조합과 스킬 운용이 궁금합니다. 초보 기준으로 추천 부탁드립니다.', 'QUESTION', 'Guardian', 730, 12, 5, FALSE, 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO comments (id, post_id, user_id, author, content, status)
VALUES
  (1, 1, 1, 'Rainfall', '세팅이 깔끔하네요. 참고하겠습니다.', 'ACTIVE'),
  (2, 1, 1, 'BlueShield', '공지 내용이 보기 좋아서 저장해 둡니다.', 'ACTIVE'),
  (3, 2, 1, 'HolySong', '파티 조건이 잘 맞으면 참여하고 싶습니다.', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;
